spring:
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.34.103:8848
        register-enabled: true
      config:
        server-addr: 81.70.34.103:8848
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.34.103:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Lx123456.
  data:
    redis:
      host: 81.70.34.103
      port: 6379
      password: Lx123456.

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl