server:
  port: 8501
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.219.158:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Lx123456.
  data:
    redis:
      host: 81.70.34.103
      port: 6379
      password: Lx123456.
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/captcha
  minio:
    endpoint: http://82.156.219.158:9000
    accessKey: minioadmin
    secretKey: lx123456.
    bucketName: mall-file
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl